### ISSUE TITLE
Auto Linking

### ISSUE THREAD

**Issue by schie** [wix/react-native-keyboard-input#101]
Does this work react native's [Auto Linking](https://github.com/react-native-community/cli/blob/master/docs/autolinking.md)?

I didn't see anything in the documentation but manual installation.

**Comment by ggunti** [comment]
@schie 
Autolinking is not working.
If you want to make it work on android with RN 0.60+:
1. Update your dependencies in `android/app/build.gradle`:
```
dependencies {
  // Add this dependency:
  compile project(":reactnativekeyboardinput")
}
```
2. Update your `android/settings.gradle`:
```
include ':reactnativekeyboardinput'
project(':reactnativekeyboardinput').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-keyboard-input/lib/android')
```
3. In your `MainApplication.java`, add:
```
import com.wix.reactnativekeyboardinput.KeyboardInputPackage;
```
4. In your `MainApplication.java`,  add to the following function:
```
  private MainApplication getThis() {
    return this;
  }
```
5. In your `MainApplication.java`, inside `getPackages()` add:
```
packages.add(new KeyboardInputPackage(getThis()));
```

See my `MainApplication.java` example:
<img width="988" alt="Captură de ecran din 2020-04-06 la 12 13 27" src="https://user-images.githubusercontent.com/26307699/78542692-343d7f00-7800-11ea-9e08-30ed458f3828.png">

**Comment by M-i-k-e-l** [comment]
Hi @schie,

[We](https://github.com/wix/react-native-ui-lib/) are in the process of migrating this library, it is not yet complete, but the auto linking works there.

Thanks @ggunti for the help, we're not going to fix this here, sorry.

**Comment by react06** [comment]
@ggunti my issue is as I import the KeyboardInputPackage, it says the package does not exist even after syncing the project with the Gradle files. Any solutions regarding this will be appreciated. Thank you.
