### ISSUE TITLE
[RN 0.60+] How to make it work on iOS?

### ISSUE THREAD

**Issue by ggunti** [wix/react-native-keyboard-input#102]
Installation instructions does not work on RN 0.60+ because of autolinking (README should be updated).
Although, I was able to successfully install this package on android, based on [this](https://github.com/wix/react-native-keyboard-input/issues/101#issuecomment-609674588) steps.

But on iOS I was unable to install it. I made the following steps:
1. `npm i --save react-native-keyboard-input`
2. `cd iOS && pod install`

But it does not work:
<img width="315" alt="Captură de ecran din 2020-04-06 la 18 39 39" src="https://user-images.githubusercontent.com/26307699/78576929-06732d00-7836-11ea-8956-adbbf81412af.png">

Also I tried the steps described in README, but it fails to build (because of RN0.60+ autolinking).

So my question is: how this package should be installed on iOS for RN0.60+?

```
  "dependencies": {
    "react": "16.11.0",
    "react-native": "0.62.0",
    "react-native-autogrow-textinput": "^5.3.0",
    "react-native-keyboard-input": "^6.0.0",
  },
```

**Comment by samgermain** [comment]
I got it working with cocoapods. I ignored all the instructions listed for installing on iOS and added 

```
pod 'ReactNativeKeyboardInput', :path => '../node_modules/react-native-keyboard-input'
pod 'ReactNativeKeyboardTrackingView', :path => '../node_modules/react-native-keyboard-tracking-view'
```

to my podfile

**Comment by ggunti** [comment]
@samgermain Thank you!
I added
```
pod 'ReactNativeKeyboardInput', :path => '../node_modules/react-native-keyboard-input'
pod 'ReactNativeKeyboardTrackingView', :path => '../node_modules/react-native-keyboard-tracking-view'
```
as you suggested and then I ran `pod install` inside `ios` directory.

I get an error message regarding autolinking when I run `react-native run-ios`, but it works.
