### ISSUE TITLE
toggleExpandedKeyboard Crash

### ISSUE THREAD

**Issue by mronline** [wix/react-native-keyboard-input#104]
I applied the demo. But "Toggle Full-Screen!" If I press the button the application crashes
React Native: 0.60
Simulator: iPhone 11 Pro mx - 13.2.2

**Comment by M-i-k-e-l** [comment]
Hi @mronline,

Yes, the `KeyboardRegistry.toggleExpandedKeyboard` is an experimental feature, you can see a better documentation [here](https://github.com/wix/react-native-ui-lib/blob/master/lib/components/Keyboard/KeyboardInput/KeyboardRegistry.ts#L117-L122).

[We](https://github.com/wix/react-native-ui-lib/) have not fully migrated this library yet, but this feature will probably be removed in future a version.

**Comment by fukemy** [comment]
hi @M-i-k-e-l , the document link is 404, could u provide other link please

**Comment by M-i-k-e-l** [comment]
Fixed
