### ISSUE TITLE
Show toolbar only when keyboard is opened. How?

### ISSUE THREAD

**Issue by ggunti** [wix/react-native-keyboard-input#108]
Hello!
I want to show the toolbar only when keyboard is opened. Otherwise, I want to hide it. Is it possible?

<img width="317" alt="Captură de ecran din 2020-05-12 la 19 29 10" src="https://user-images.githubusercontent.com/26307699/81720683-69845f00-9487-11ea-9046-7065b7404e05.png">

Thank you!

**Comment by M-i-k-e-l** [comment]
This is more of a user's code and not a library code question, but [this](https://gist.github.com/M-i-k-e-l/052b493650695ae2f53bedd21717c2a1) is a start. It's still not perfect, you'll see a small hiccup when returning from a custom keyboard to the regular one, but I'll leave that to you.

**Comment by ggunti** [comment]
@M-i-k-e-l 
Thank you, it works!
I was able to easily solve also the hiccup.
