### ISSUE TITLE
KeyboardTrackingScrollBehaviorScrollToBottomInvertedOnly keeps scroll momentum on open

### ISSUE THREAD

**Issue by Thorbenandresen** [wix/react-native-keyboard-input#13]
Hi @artald!

**Repro**
1. open chat thread
2. scroll up fast
3. open keyboard with iOSScrollBehavior =  KeyboardTrackingScrollBehaviorScrollToBottomInvertedOnly

**Expected**
* no more scroll momentum like in iMessage

**Actual**
* the keyboard scrolls the scrollview to bottom (like expected) but the scroll momentum remains, i.e. it continues to scroll up until no momentum diminished.

**Comment by artald** [comment]
hey @Thorbenandresen 

I was not able to reproduce a similar behavior. I tried it with a normal ScrollView (with some hacks on  the native side to allow it to work on non-inverted).

Hard to tell the reason, but maybe it has something to do with the inversion.

Although I don't think this is really an issue (as long as the scroll to bottom actually works 😄) , I can push an attempt for a fix that will stop the current scroll before scrolling to bottom.

What do you think?

**Comment by Thorbenandresen** [comment]
Hey @artald, thank you!

its is not that easy to repro on the simulator. Here a video of running it on device: https://www.youtube.com/watch?v=tVIigjlUJEU&feature=youtu.be

here is the code: 
https://gist.github.com/Thorbenandresen/f6de57dd92d0670ba12b8893c468dffa

Can you push a fix if there is an easy way to disable it (though a prop e.g.?  just incase the fix has unintended sideeffects...

**Comment by artald** [comment]
Thanks for the vid @Thorbenandresen !

Let's try something different - try to apply the following fix locally and let me know if this helps:

1. Open the demo Xcode project.
2. In the project navigator (folder structure on the left) open `Libraries`, then open `KeyboardTrackingView.xcodeproj` and select `KeyboardTrackingViewManager.m` so it's visible in the editor.
3. go to line 339 (should be where `observingInputAccessoryViewKeyboardWillAppear` method starts. Add this line of code right before line 345:
`[self.scrollViewToManage setContentOffset:self.scrollViewToManage.contentOffset animated:NO];`

The complete method should look like this:
```objective-c
-(void)observingInputAccessoryViewKeyboardWillAppear:(ObservingInputAccessoryView *)observingInputAccessoryView keyboardDelta:(CGFloat)delta
{
    if(self.scrollViewToManage != nil)
    {
        if(self.scrollBehavior == KeyboardTrackingScrollBehaviorScrollToBottomInvertedOnly && _scrollIsInverted)
        {
            //possible solution for issue #13 ?
            [self.scrollViewToManage setContentOffset:self.scrollViewToManage.contentOffset animated:NO];
            
            self.scrollViewToManage.contentOffset = CGPointMake(self.scrollViewToManage.contentOffset.x, -self.scrollViewToManage.contentInset.top);
        }
        else if(self.scrollBehavior == KeyboardTrackingScrollBehaviorFixedOffset)
        {
            self.scrollViewToManage.contentOffset = CGPointMake(self.scrollViewToManage.contentOffset.x, self.scrollViewToManage.contentOffset.y + delta * (self.scrollIsInverted ? -1 : 1));
        }
    }
}

```

Now build and run the project...

This is supposed to stop the current scroll before scrolling to bottom and it shouldn't break anything else.

**Comment by Thorbenandresen** [comment]
@artald - thanks a lot, that does fix it for us. Can you release this fix?

**Comment by artald** [comment]
Done. Available in `react-native-keyboard-tracking-view` version `3.0.8`
