### ISSUE TITLE
Android: Previous layout was ignored! crasher

### ISSUE THREAD

**Issue by Thorbenandresen** [wix/react-native-keyboard-input#14]
I don't have a solid repro case for this yet, but I get this crasher sometimes on Android.

Maybe this is already fixed by 3.0.8? 

![img_5716](https://cloud.githubusercontent.com/assets/8238976/25351675/62881be6-28f7-11e7-8c7f-d8697575b871.JPG)

**Comment by artald** [comment]
Hey,
There was a fix for an Android crash in 3.0.8. Not totally sure it's the same one though..
Please update and see if you can reproduce. Thanks!

**Comment by Thorbenandresen** [comment]
@artald thanks, I'll reopen if I see it again.
