### ISSUE TITLE
Unwanted behavior on overscroll 

### ISSUE THREAD

**Issue by Thorbenandresen** [wix/react-native-keyboard-input#15]
Repro

* open iOS demo App
* go to custom keyboard "show1" or "show2"
* over scroll down

Actual 
* keyboard resets and I loose my touch event on the the scrollview

Expected
* behavior when doing the same repro case while the native keyboard is shown.

**Comment by artald** [comment]
Yup that's a bug.

Notice that the demo app uses the `revealKeyboardInteractive` flag on `KeyboardAccessoryView`. This is a fun feature that lets you drag the scroll to open the keyboard. In case the keyboard is already open and you perform the drag, the native code still tries to apply this behavior which causes the input to gain focus and reset the keyboard.

I'll push a fix, thanks.

**Comment by artald** [comment]
this is fixed with `react-native-keyboard-tracking-view` version `3.0.9`
