### ISSUE TITLE
Prevent textinput from auto focusing when scrolling down

### ISSUE THREAD

**Issue by henry-whil** [wix/react-native-keyboard-input#21]
In the demo, if the view becomes scrollable, scrolling down will auto trigger the textinput to focus, which then shows the keyboard.  Is there a way to prevent this behavior?

**Comment by artald** [comment]
Yes, if you don't want this behavior you can remove the `revealKeyboardInteractive` prop from `KeyboardAccessoryView`.

**Comment by sinay18** [comment]
I couldn't do it and i am struggling with this....could someone help please?
