### ISSUE TITLE
Is this usable as system keyboard in other apps?

### ISSUE THREAD

**Issue by supunucsc** [wix/react-native-keyboard-input#27]
Hi, I want to use this as a keyboard for other apps. Basically I want to install this as a keyboard to be used with other apps?? Will it be possible?

**Comment by artald** [comment]
This package allows you to use a custom keyboard within your own app. While it can be a good starting point for showing a custom view inside the keyboard input space, there are other necessary requirements before you can turn it to a system wide keyboard that can be used in other apps.

On iOS, for example, a custom keyboard is an app extension. You can see more info [here](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/CustomKeyboard.html).

Currently there is no plan to add support for this case in this package.
