### ISSUE TITLE
Different behavior on iOS simulator vs. physical device

### ISSUE THREAD

**Issue by adamgrossman** [wix/react-native-keyboard-input#32]
When I'm testing out my app and using the keyboard in the iOS simulator, everything works great. However, when I switch over to testing it out on my physical phone, the text input stays at the bottom of the screen and the keyboard lays on top of it. 

**Screenshot of iOS simulator**
<img width="266" alt="screen shot 2017-11-09 at 9 29 30 am" src="https://user-images.githubusercontent.com/8585262/32621408-91a3cb12-c534-11e7-815e-8165c58bc61d.png">

**Screenshot of physical device**
<img width="188" alt="screen shot 2017-11-09 at 9 57 00 am" src="https://user-images.githubusercontent.com/8585262/32621409-91be2bce-c534-11e7-8b27-3abf52add21f.png">

I'm using a `<KeyboardAccessoryView>` with `<AutoGrowingTextInput>` within it.

Has anyone experienced similar behavior?

**Comment by adamgrossman** [comment]
This was a xcode config issue on my mind. Nevermind!

**Comment by michaelcurtis** [comment]
@adamgrossman Mind sharing what the config issue was? I'm seeing the same thing.

**Comment by adamgrossman** [comment]
@michaelcurtis this was a while back, but I believe my issue was not linking the library properly (https://github.com/wix/react-native-keyboard-input#ios). 

Good luck!

**Comment by michaelcurtis** [comment]
@adamgrossman Thanks for taking the time to reply! Figured out my issue is #74.
