### ISSUE TITLE
 Crash in  RN 0.53 iOS

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [wix/react-native-keyboard-input#41]
'[<RCTTextView 0x7fa5b0c91a30> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _backedTextInput.'
*** First throw call stack:

**Comment by artald** [comment]
should be fixed now with version `5.2.0`

**Comment by giantss** [comment]
@artald @Darkhorse-Fraternity 
 "react-native-keyboard-input": "^5.2.3",
Still will crash.
