### ISSUE TITLE
FlatList not responding to keyboard (looking for help)

### ISSUE THREAD

**Issue by davidpaulsson** [wix/react-native-keyboard-input#45]
So I'm sure I've probably missed something, but I'd like to never cover any content with the keyboard. Basically, KeyboardAvoidingView's `behavior="padding"`, but I cannot figure out to implement it with KeyboardAccessoryView.

Attaching gif to illustrate (this is what I have, not the behavior I want :))
![kapture 2018-04-10 at 15 24 31](https://user-images.githubusercontent.com/779321/38559998-dd01d564-3cd4-11e8-928a-8f2f702b8876.gif)

My code is as following

```render() {
  return (
    <View style={{ flex: 1 }}>
      <FlatList
        inverted
        data={data}
        ...
      />
      <KeyboardAccessoryView
        renderContent={this.keyboardAccessoryViewContent}
        kbInputRef={this.textInputRef}
        kbComponent={this.state.customKeyboard.component}
        kbInitialProps={this.state.customKeyboard.initialProps}
        onItemSelected={this.onKeyboardItemSelected}
        onKeyboardResigned={this.onKeyboardResigned}
      />
    </View>
  );
```

Using
"react-native-keyboard-input": "^5.2.0"
"react": "16.0.0"
"react-native": "0.53.0"

**Comment by davidpaulsson** [comment]
Android works as I want it without any modifications.

**Comment by artald** [comment]
hey,

I'm not really sure what's going on there, but if you take a look at `KeyboardAccessoryView ` you'll notice there's a prop called `scrollBehavior`. This controls what happens to the scroll container when the keyboard is shown.

By default the behavior is set to "fixed offset", which means that the scroll container will maintain its position (I think that this is what you also want for your case), but in your gif it seems as if it's set to `none` even thought you are not overriding it.

One option that the package fails to recognize the scroll container and perform this "magic" for you :). Check if you can scroll to see the whole content or if the keyboard covers it and makes the part under the it to be unreachable - if thats the case then this is why the scroll behavior is not working.

It's also worth to mention that even though everything compiles and runs, this package wasn't tested thoroughly in RN > 0.51, so it's possible that there are issues.

**Comment by davidpaulsson** [comment]
Thank you @artald for your time!

I've tried to set `scrollBehavior`, (and `iOSScrollBehavior`) but without any success 😔 But I don't know If I'm maybe doing it wrong? I've tried with strings, like `iOSScrollBehavior={'KeyboardTrackingScrollBehaviorFixedOffset'}`, and also from NativeModules like `iOSScrollBehavior={NativeModules.KeyboardTrackingViewManager.KeyboardTrackingScrollBehaviorFixedOffset}`.

When the keyboard is open, the FlatList height seems to be the same (I can't scroll to the end to see all messages. See gif)
![kapture 2018-04-10 at 16 00 10](https://user-images.githubusercontent.com/779321/38561533-94e766dc-3cd8-11e8-974e-17f2a6d95c9c.gif)

Can I test/report anything that would help to figure out if it's broken in RN > 0.51?

**Comment by davidpaulsson** [comment]
I can try to set up a small repo reproducing this. A question: with [this coming in RN 55](https://github.com/facebook/react-native/commit/38197c8), will that change snytning going forward? It only handles the toolbar above the keyboard, not the keyboard it self, but still.

**Comment by artald** [comment]
The new RN 55 component handles showing a view that tracks the keyboard by associating it to a text input, but it doesn't handle setting a keyboard input view.

If nothing works for you, you can still use this package just for showing a custom keyboard.

**Comment by davidpaulsson** [comment]
Ok, so I did a test run with different RN versions. And it's great because they all work. Soooooo I guess it's _not_ a problem with RN, but rather something in my project. Annoying since I don't know what, but at least we can eliminate RN as a cause.

- RN51 https://github.com/davidpaulsson/react-nativekeyboard-input-issues-45
- RN52 https://github.com/davidpaulsson/react-nativekeyboard-input-issues-45/tree/rn52
- RN53 https://github.com/davidpaulsson/react-nativekeyboard-input-issues-45/tree/rn53
- RN54 https://github.com/davidpaulsson/react-nativekeyboard-input-issues-45/tree/rn54
- RN55 https://github.com/davidpaulsson/react-nativekeyboard-input-issues-45/tree/rn55

They all work.

¯\_(ツ)_/¯

**Comment by artald** [comment]
thanks for checking it with all the versions 😃 
as I understand they all work as expected... if you can create a demo that reproduces your issue I can look into it.

**Comment by davidpaulsson** [comment]
Yup, I've probably messed up along the way somehow. Will try to fix and/or reproduce it and report what I can find. Thank you for your time!

**Comment by stwiname** [comment]
@davidpaulsson did you manage to fix this? I'm having the same problem

**Comment by davidpaulsson** [comment]
Unfortunately no. I have my guesses it's because how my app is structured. We're using a mix of modals and NavigationExperimental and when there are multiple views stacked on top of each other react-native-keyboard-input does not seem to work. If I tried the same code, but as the only child in the hierarchy it _did_ work, so even though I can't say exactly what's up, I think react-native-keyboard-input adjusts/listens on the first mounted scrollview/flatlist/whatevs from the root component (and not necessarily the one in that's viewable at the moment)

**Comment by Jarred-Sumner** [comment]
having the same problem too

**Comment by Jarred-Sumner** [comment]
@davidpaulsson 

I have a hunch that a fix is:

- Set `requiresSameParentToManageScrollView` and `manageScrollView` to `true` on `<KeyboardAccessoryView />` 
- Use `renderScrollComponent` in your FlatList/SectionList/VirtualizedList and wrap the `<ScrollView />` we pass through to be a child of the same `<View />` as the `<KeyboardAccessoryView />`, so that the `KeyboardAccessoryView shares a superview with the desired ScrollView


Will try this out tomorrow.

`requiresSameParentToManageScrollView`: https://github.com/wix/react-native-keyboard-tracking-view/blob/master/lib/KeyboardTrackingViewManager.m#L177

**Comment by stwiname** [comment]
Setting `requiresSameParentToManageScrollView` to true solved it for me

@Jarred-Sumner thanks

**Comment by Jarred-Sumner** [comment]
glad to hear that worked for you @stwiname!

An update on this: https://github.com/wix/react-native-keyboard-input/issues/45#issuecomment-389452077

`requiresSameParentToManageScrollView` works...but the scroll view it thinks is the correct one is _not_ the correct one.

Specifically, I have a scrollview in the screen that precedes the screen that the `<KeyboardAccessoryView />` is on. Since it does a breadth-first search from the top of all UIView's, it finds the scrollview on the page before the the current one...and tracks scrolling of that scrollview.

When I unmounted that scrollview when it's not focused...it works. But this isn't a great solution. It would be much better if there was some way to provide a tag to a scrollview.

**Comment by Jarred-Sumner** [comment]
I have a fix for this issue in this PR: https://github.com/wix/react-native-keyboard-tracking-view/pull/15

**Comment by davidpaulsson** [comment]
I'd just like to say this is working now thanks to your PR @Jarred-Sumner landing in `react-native-keyboard-tracking-view` v5.4.4. Thank you very much for your effort! Will close this now. ❤️

**Comment by alexandregiordanelli** [comment]
@davidpaulsson can you share the final code?

**Comment by stanislav-sidorov-empeek** [comment]
another solution, measure keyboard height and add margin-bottom to FlatList container:

```<KeyboardAvoidingView` behavior={'height'}><FlatList /></KeyboardAvoidingView>```

```
  const handleShowKeyboard = (e: KeyboardEvent) => {
    const height = e.endCoordinates.height;
    setKeyboardHeight(height);
  };

  const handleHideKeyboard = () => {
    setKeyboardHeight(0);
  };

  React.useEffect(() => {
    if (IS_ANDROID) {
      return;
    }
    const keyboardDidShowSubscribtion = Keyboard.addListener(
      'keyboardDidShow',
      handleShowKeyboard,
    );
    const keyboardWillHideSubscribtion = Keyboard.addListener(
      'keyboardWillHide',
      handleHideKeyboard,
    );
    return () => {
      Keyboard.removeSubscription?.(keyboardDidShowSubscribtion);
      Keyboard.removeSubscription?.(keyboardWillHideSubscribtion);
    };
  }, []);

```
  
  also for IPhone X need to get to attention a height of the home indicator
