### ISSUE TITLE
Changing orientation doesn't update input

### ISSUE THREAD

**Issue by diegolmello** [wix/react-native-keyboard-input#49]
Hey, guys.
Take a look at this gif.

![apr-26-2018 10-45-57](https://user-images.githubusercontent.com/804994/39309719-167d2188-493f-11e8-90a7-1afef664de40.gif)

As you can see, message box input keeps the same width after orientation changes.
I tried `this.forceUpdate()`with no luck :(

Can you help me?

**Comment by artald** [comment]
Hi @diegolmello,

I'll try to look into it this week. It's most likely some flex issue in the JS styles.

**Comment by artald** [comment]
sorry about the delay. a fix is now available in `v5.2.3`.

**Comment by diegolmello** [comment]
@artald Thanks, man. Awesome job!
