### ISSUE TITLE
Compatibility issue with Typescript? 

### ISSUE THREAD

**Issue by Thorbenandresen** [wix/react-native-keyboard-input#7]
I am using a Typescript in my project and I get the following issue. Requiring KeyboardAccessoryView and initializing it crashes my packager and writes this error to the terminal

```
[1] [4/5/2017, 10:39:52 AM] <START> Transforming files
[1] /Users/thorbenandresen/Documents/myProject/node_modules/babylon/lib/index.js:4336
[1]   throw err;
[1]   ^
[1]
[1] SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
```

I don't know if this is an issue with this repo or an issue on my end. 

**Current workaround**
Copy & paste the src folder from node_modules to my own source folder and import the files directly

**Comment by artald** [comment]
I'm pretty much sure it's not this specific package, but I don't know.

If you have a .babelrc file in your project - try to delete it, then restart the packager with the --reset-cache flag.

**Comment by artald** [comment]
@Thorbenandresen did my suggestion help? can we close this?

**Comment by Thorbenandresen** [comment]
@artald just as an update, we still need our babel.rc for now so we have not been able to test that yet.

**Comment by artald** [comment]
@Thorbenandresen bable.rc options can be specified in your package.json instead.
I'm just curious to know if it solves this issue...

**Comment by artald** [comment]
@Thorbenandresen any news about this issue? can we close this?

**Comment by Thorbenandresen** [comment]
Still haven't gotten around to test it. I can re-open if this doesn't work.

**Comment by artald** [comment]
cool ,no pressure on closing the issue, just wanted to see if you got it sorted out or not

**Comment by Thorbenandresen** [comment]
@artald - thanks, that worked. Do you know why babel.rc was causing this issue?

**Comment by artald** [comment]
@Thorbenandresen i'm not completely sure why this happens, but I had a similar issue in the past and removing babel.rc did the trick.

I guess it's something between how RN packager works with babel, probably something in the JS code of this package is causing some sort of conflict for the packager.

If really necessary I guess that transpiling the JS code would also solve this, but I rather not do it unless it's completely necessary.

**Comment by Thorbenandresen** [comment]
@artald - thanks and no worries. babel.rc settings in package.json works just as fine for us.
