### ISSUE TITLE
keyboardListeners are called multiple times

### ISSUE THREAD

**Issue by Thorbenandresen** [wix/react-native-keyboard-input#8]
Hi again,

if I add keyboardListeners to the the demoApp like below, I can see that both are called 3 times. Does that also happen for you?

My problem is that I scroll a view based on the those events, so calling those scrolling function introduces some jankiness. 

```js

  componentWillMount() {

    const showEvent = IsIOS ? 'keyboardWillShow' : 'keyboardDidShow';
    const hideEvent = IsIOS ? 'keyboardWillHide' : 'keyboardDidHide';

    if (IsIOS) {
      this.keyboardEventListeners = [
        Keyboard.addListener(showEvent, () => console.log('keyboardWillShow')),
        Keyboard.addListener(hideEvent, () => console.log('keyboardWillHide')),
      ];
    } else {
      this.keyboardEventListeners = [
          Keyboard.addListener(showEvent, this.props.handleKeyboardOpen.bind(this)),
          Keyboard.addListener(hideEvent, this.props.handleKeyboardClose.bind(this)),
      ];
    }

  }
```

RN 0.38

**Comment by artald** [comment]
Yes, getting it 3 times, but I think that it is normal and not unique for this project. If you take a look at the event that's received:
```
1. '{"easing":"keyboard","endCoordinates":{"screenY":326.5,"screenX":0,"width":375,"height":340.5},"startCoordinates":{"screenY":667,"screenX":0,"width":375,"height":340.5},"duration":250}'

2. '{"easing":"keyboard","endCoordinates":{"screenY":409,"screenX":0,"width":375,"height":258},"startCoordinates":{"screenY":326.5,"screenX":0,"width":375,"height":340.5},"duration":250}'

3. '{"easing":"keyboard","endCoordinates":{"screenY":326.5,"screenX":0,"width":375,"height":340.5},"startCoordinates":{"screenY":409,"screenX":0,"width":375,"height":258},"duration":0}'
```

You can see that the endCoordinates and startCoordinates change, also the height.

What exactly is the use case of using the events here? what kind of scrolling is involved?

**Comment by artald** [comment]
I think you're right, when using just a text input without a KeyboardAccessoryView, the event is received only once.

Could be that it's because of the native handling we're doing to allow the proper tracking of the toolbar (which also allows the interactive drag).

I'll see if we can look into it

(cc @LeoNatan)

**Comment by Thorbenandresen** [comment]
@artald yes - it is a chat app and we need to adjust the scroll position (i.e. scrolling to bottom) whenever the keyboard is shown or hidden. "FixedOffset" / "Position" mode does currently not work for us because we need to display the chat bubbles at the top when there are only a few chat bubbles in a thread  (i.e. not scroll down).

**Comment by artald** [comment]
@Thorbenandresen are you using an inverted scroll? If not - how are you scrolling to bottom (assuming you're using a `ListView`)?

**Comment by LeoNatan** [comment]
This seems like iOS behavior. Whenever the the keyboard frame changes, iOS sends a notification. It seems that playing around with the input views makes the system send some intermediary frames. Not sure what we can do to correct this, as this seems like the internal behavior.

@Thorbenandresen I suggest find a way to use an inverted scroll view and let our system scroll it in native. JavaScript scrolling by itself creates latency and jank between keyboard showing and scroll view actually scrolling.

**Comment by LeoNatan** [comment]
Another option is to use https://github.com/wix/react-native-keyboard-tracking-view and then use that for observing keyboard height changes, but I don't think we have notifications set up in there yet.

**Comment by artald** [comment]
@LeoNatan that's a nice idea, we can expose it from the keyboard-input package too.
But I am not sure it would help because you would still get the same 3 notifications.

RN also has keyboard listeners as you know, they get the same notifications and report to JS, so maybe there's no point in duplicating that.

**Comment by LeoNatan** [comment]
Yes, but since we use a different method to determine keyboard height and position (by superview observation), we can only send our notification when there is a real change. 
It should not replace system notifications (we cannot do anything about those), but we can offer alternative ones.

**Comment by artald** [comment]
True, this we can do.

Still I have to agree again that the best way to do it would be to go with inverted scroll and our native solution for scroll to bottom 😃

**Comment by Thorbenandresen** [comment]
Thanks a lot! Cool, I will defiantly checkout the an inverted scroll view

**Comment by artald** [comment]
Cool. You basically do something like this:
```
import InvertibleScrollView from 'react-native-invertible-scroll-view';
...
<ListView
        dataSource={this.state.ds}
        renderRow={this.props.renderMessage}
        style={{flex: 1}}
        renderScrollComponent={props => <InvertibleScrollView {...props} inverted/>}
/>
```
But, you'll probably also need to invert your data (depends on how you use it atm).
Without a similar approach I think it will be nearly impossible to do a real scroll to bottom on a pure JS ListView.

We have a very similar component we've just started working on. You can take a look but take into account that it's still at a very early stage and WIP: https://github.com/wix/react-native-chat-listview/blob/master/src/index.js

Closing this for now. You can re-open if it's still an issue in the future.

**Comment by Thorbenandresen** [comment]
@artald @LeoNatan - thx for all the suggestions and I agree that an inverted scroll view is the way to go. btw. version 2.0.6 does call keyboardWillShow only once, and keyboardWillHide twice.

**Comment by artald** [comment]
Yes, I know. The tracking part was rerwritten to provide proper interactive scroll and drag of the keyboard, and allow us to add some more advanced features. On v2 and below it was a simple approach to tracking and it was greatly improved
