### ISSUE TITLE
Using this package with second Text Input in KeyboardAccessoryView

### ISSUE THREAD

**Issue by Thorbenandresen** [wix/react-native-keyboard-input#9]
This more a feature idea than an issue. 

I have another Text Input in the KeyboardAccessoryView for Gif Search.

**Example**

![simulator screen shot apr 5 2017 5 35 43 pm](https://cloud.githubusercontent.com/assets/8238976/24728204/ff567d58-1a26-11e7-95ba-ca7cd4cb11e2.png)

The problem is, that if this second TextInput is focused and I dismiss the keyboard, the KeyboardAccessoryView will stain in place (no matter if I use keyboardDismissMode 'interactive' or 'on-drag'.) 

This worked for me with `keyboardDismissMode = {'on-drag'}` on version 2 releases.

![simulator screen shot apr 5 2017 5 43 53 pm](https://cloud.githubusercontent.com/assets/8238976/24728512/31db901e-1a28-11e7-9ed2-0e919e492d66.png)

**Comment by artald** [comment]
First off - this is really cool! can you also put some screenshots of the other keyboards (image gallery for example)? 😃 

It would greatly help if you can put a gist of a working example that switches between normal input and the other (gif) input. Would make it easier for us to take a quick look at what's going on there, hopefully we can turn up with a solution.

**Comment by Thorbenandresen** [comment]
@artald - thanks. Sure, I will send you some screenshots once they are done. I started out with giphy integration :) I will be on vacation the rest this week, so hopefully I got something end of next week .

So I hacked together a (buggy) version of the the gif search here: https://gist.github.com/Thorbenandresen/cc36c3b26e806d2a0affbc9090c7336d

The second text input being focused does NOT break the 'interactive' nor 'on-drag' scrolling, so the issue must be on my side. 

Thanks!

**Comment by artald** [comment]
Awesome, thanks!
If you do find out what breaks your own implementation - let me know. It's highly possible that there are hidden issues with more complex layouts / multiple inputs, and if we have a reproducing gist we can figured it out.

Enjoy your vacation!
