### ISSUE TITLE
🐞ANDROID SCREEN FLICKERING ON KEYBOARD CHANGE

### ISSUE THREAD

**Issue by OmarBasem** [wix/react-native-keyboard-input#98]
When toggling keyboards, the screen flashes on android. It happens randomly.

**Comment by ggunti** [comment]
Also at me. On iOS I was unable to install this package at all. I use RN0.62.

**Comment by M-i-k-e-l** [comment]
Hi @OmarBasem,

Thanks for reporting this issue, however it is a duplicate of https://github.com/wix/react-native-keyboard-input/issues/94.
I will close this issue, please add any helpful information you have in that ticket.
